name: Update major tag

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
defaults:
  run:
    shell: pwsh
permissions:
  contents: write

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Update the ${{ env.TAG_NAME }} tag
        id: update-major-tag
        uses: actions/publish-action@v0.4.0
        with:
          source-tag: ${{ env.TAG_NAME }}
